# Generated by Django 5.0.1 on 2024-01-24 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_room_chair'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='chair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_app.chair'),
        ),
    ]
