# Generated by Django 5.0.1 on 2024-02-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_alter_chair_options_chair_chair_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chair',
            options={'ordering': ['chair_number']},
        ),
    ]
