# Generated by Django 5.0.1 on 2024-02-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_alter_chair_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
