# Generated by Django 5.0.1 on 2024-01-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_event_chair'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='isVIP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chair',
            name='taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chair',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
