# Generated by Django 5.0.1 on 2024-01-24 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_chair_isvip_chair_taken_alter_chair_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chair',
            old_name='taken',
            new_name='isTaken',
        ),
        migrations.AddField(
            model_name='chair',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='chair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_app.chair'),
        ),
    ]
