# Generated by Django 5.0.1 on 2024-02-04 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_room_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chairs', to='event_app.room'),
        ),
    ]
